YWLM ops, other misc changes
vatpac-technology/sops pull request #189
Opened 2023-12-04 01:01 UTC by alphadelta332

## Summary
Major changes to YWLM operations in line with AIRAC 2312. Other miscellaneous changes.

## Changes
**Fixes**:
- BIK -> CB TCU Standard Assignable level corrected to be `F130` on **BIK** page
- Minor typos in **TL TCU** page
- Minor typos in **AD TCU** page

**Changes**:
- Major changes to **WLM TCU** page associated with airspace changes and new SIDs/STARS
- Major changes to **ARL** page associated with airspace changes and new YWLM SIDs/STARS
- **SY TCU** now responsible for assigning STARs to aircraft inbound to YWLM
- Aircraft departing 14R at **YMLT** now assigned **BRAVO** SID by default
- Standardised formatting of auto-release coordination in **TCU pages**

**Additions**:
- Annotations
    - Track Extended Centreline (_**TEC**_)
    - Visual (_**V**_)
    - Runway in Sight (_**R**_)

2023-12-04 01:46 UTC, LeGiraffe submitted a review, later dismissed

2023-12-04 03:14 UTC, JoshuaMicallefYBSU submitted a review, later dismissed

2023-12-04 10:41 UTC, mattkelly4 requested changes

2023-12-04 10:41 UTC, mattkelly4 commented on docs/military/williamtown.md
> +When WLM ADC is online, they own the within the WLM MIL CTR A (`SFC`-`A050`). This may be amended/released as required between WLM ADC and WLM TCU.
Typo (missing 'airspace')

2023-12-04 10:41 UTC, mattkelly4 commented on docs/military/townsville.md
> +Runway 07/25 is often used in conjunction with 01 for VFR arrivals and Helicopter Traffic.
I guess if we put 25 there, we'd need to reference 19 as well (you wouldn't use 25 and 01 together) which becomes redundant, so maybe just 'Runway 07/25 is often used for VFR arrivals and helicopter traffic.'

2023-12-04 10:41 UTC, mattkelly4 commented on docs/aerodromes/Launceston.md
> +Aircraft planned via **IRSOM** **MORGO**, **ONAGI**, **VIMAP**, **NUNPA**, or **MOTRA**, departing Runway 32L, shall be assigned the relevant **ALPHA** Procedural SID.
Missing comma after IRSOM

2023-12-04 23:56 UTC, mattkelly4 approved these changes

2023-12-05 02:07 UTC, LeGiraffe approved these changes

2023-12-09 12:38 UTC, JoshuaMicallefYBSU approved these changes

2023-12-09 12:38 UTC, merged