Page title tidy up
vatpac-technology/sops pull request #200
Opened 2023-12-18 01:01 UTC by mattkelly4

`Notify` tag not required. Just tidied up the page title and made a few formatting changes.

2023-12-18 01:13 UTC, JoshuaMicallefYBSU approved these changes

2023-12-18 01:54 UTC, alphadelta332 approved these changes

2023-12-18 19:06 UTC, LeGiraffe submitted a review, later dismissed

2023-12-19 02:23 UTC, alphadelta332 requested changes
As discussed by PM

2023-12-20 23:23 UTC, mattkelly4 commented
> As discussed by PM

Updated

2023-12-21 00:00 UTC, alphadelta332 approved these changes

2023-12-21 00:46 UTC, LeGiraffe approved these changes

2023-12-21 00:46 UTC, LeGiraffe commented on docs/aerodromes/Amberley.md
>      WOLF03 was assiged the BYRON7 departure with their initial clearance.
Does Mil do this differently or should "Make Left Turn" be after "Cleared For Takeoff"?

2023-12-21 06:31 UTC, JoshuaMicallefYBSU approved these changes

2023-12-21 06:31 UTC, merged