HUO
vatpac-technology/sops pull request #26
Opened 2022-11-01 05:00 UTC by tylerthetiletiler

HUO Page added
PIY Grammer mistake fixed
TODO page (Please stop changing the spelling of Coffs Harbour back to "Harbor")

2022-11-01 05:03 UTC, chrisg06 commented on docs/enroute/Melbourne Centre/HUO.md
> +Aircraft not arriving via a STAR must be coordinated in accordance with the Coordination procedure.
Link to coordination procedure page

2022-11-01 05:55 UTC, alexd-332 requested changes

2022-11-01 05:55 UTC, alexd-332 commented on docs/terminal/Tassie TCU/operations.md
> +
Note about airspace dimensions, CTA LL F125

2022-11-01 05:55 UTC, alexd-332 commented on docs/terminal/Tassie TCU/coordination.md
> +**Departing All Ports** - Assigned the lower of `F130` or `RFL`
F120 if CTA LL is F125

2022-11-01 06:10 UTC, alexd-332 requested changes

2022-11-01 06:10 UTC, alexd-332 commented on docs/terminal/Tassie TCU/coordination.md
> +YMLT Arrivals: `F130`
A090 for YMLT

2022-11-01 06:25 UTC, alexd-332 approved these changes
Nice

2022-11-01 06:51 UTC, alexd-332 approved these changes

2022-11-02 02:33 UTC, zachbf commented on docs/terminal/Tassie TCU/operations.md
> +Visual approaches are preferred into Launceston, if due to operational requirements, an aircraft is unable to accept a visual approach, Coordination with **LT ADC** may be required.
Launy has no STARs, however aircraft are now often instructed to track for 32L via IRSOM, NODAS, MLTSC which keeps the aircraft within CTA and away from the departures stream. 32L is usually the favourable runway. I expect launcy to have STARs at some point in the near future.

2022-11-02 03:57 UTC, zachbf approved these changes

2022-11-02 03:59 UTC, merged