Added SOP for CPDLC Functionality with vatACARS
vatpac-technology/sops pull request #260
Opened 2024-06-14 14:23 UTC by tylerthetiletiler

## Summary
Added SOP for CPDLC Functionality with vatACARS

## Changes

**Additions**:
- Adding CPDLC Controller Skills page inline with vatACARS release for use on the network
- Amended ENR pages to include CPDLC section

2024-06-14 14:24 UTC, tylerthetiletiler commented
Please do not merge, I will do it once given the Ok from the vatACARS team :)

2024-06-14 18:49 UTC, alphadelta332 requested changes

2024-06-14 18:49 UTC, alphadelta332 commented on docs/controller-skills/cpdlc.md
> +| PIY | YPIY | **CPDLC** |
Should be Voice (arrivals sector)

2024-06-14 18:49 UTC, alphadelta332 commented on docs/enroute/Brisbane Centre/ARL.md
> +        Even though ARL's Primary Communication Method is Voice, CPDLC should be used for Overfliers.
I feel like 'may' is a better choice of wording than 'should', but if you prefer to encourage its use then no worries

2024-06-14 18:49 UTC, alphadelta332 commented on docs/enroute/Melbourne Centre/PIY.md
> +The Primary Communication Method for PIY is [CPDLC](../../controller-skills/cpdlc.md).
Voice

2024-06-14 18:50 UTC, tylerthetiletiler commented on docs/controller-skills/cpdlc.md
> +| PIY | YPIY | **CPDLC** |
OLW or PIY? or both

2024-06-14 19:01 UTC, alphadelta332 requested changes

2024-06-14 19:01 UTC, alphadelta332 commented on docs/enroute/Brisbane Centre/TRT.md
> +The Primary Communication Method for TRT is Voice.
Sorry missed this on the first go. Table on the CPDLC page has CPDLC as primary. Honestly it's probably halfway in between, so up to you which one you go

2024-06-14 19:59 UTC, alphadelta332 approved these changes

2024-06-15 03:46 UTC, chrisg06 approved these changes

2024-06-15 03:56 UTC, zkgell approved these changes

2024-06-15 03:56 UTC, zkgell commented on docs/controller-skills/cpdlc.md
> +**Station Code:** Must be the identifier of the airport which is being controlled.
Of the position being controlled?

2024-06-15 11:31 UTC, merged