Main Changes
vatpac-technology/sops pull request #284
Opened 2024-08-04 00:35 UTC by Augzer

## Summary
Made IFR level assignment for YPDN and Off-Mode departure changes for YMML,

## Changes
**Changes**:
- Changed DN ADC to TCU IFR level assignment to be more concise.
- Clarified Off-mode SID assignment.

**Additions**:
- Added Image to demonstrate SID conflict and resolution at YMML.

2024-08-04 00:36 UTC, Augzer commented
I included line 52 in the ML ADC page to help clarify however its undecided if its necessary so It's just an option for the final PR.

2024-08-04 05:04 UTC, alphadelta332 requested changes

2024-08-04 05:04 UTC, alphadelta332 commented on docs/aerodromes/classc/Melbourne.md
> +![IPSEG1 SID](img/IPSEG1SID.png){ width="700" }
ISPEG typo

2024-08-04 05:04 UTC, alphadelta332 commented on docs/aerodromes/classc/Melbourne.md
> +  <figcaption>Runway 16 and 27 departure conflicts visualised with the IPSEG1 SID</figcaption>
ISPEG typo

2024-08-04 05:14 UTC, alphadelta332 approved these changes

2024-08-04 07:05 UTC, JoshuaMicallefYBSU approved these changes

2024-08-05 13:59 UTC, mattkelly4 approved these changes

2024-08-05 13:59 UTC, merged

2024-08-05 14:09 UTC, tylerthetiletiler approved these changes