Cairns Rewrite
vatpac-technology/sops pull request #293
Opened 2024-08-20 07:53 UTC by mattkelly4

## Summary
Updates the Cairns procedures to remove outdated information and add additional details & examples for a variety of scenarios.

## Changes
**Fixes**:
- Improves clarity of Cairns Aerodrome and TCU pages

**Additions**:
- Helicopter operations to The Pier
- Operational notes and coordination requirements for visual approaches
- YBCS STAR clearance advice for KEN

**Removals**:
- Trinity Airspace release (now released by default)

2024-08-20 08:02 UTC, tylerthetiletiler submitted a review, later dismissed

2024-08-20 12:00 UTC, alphadelta332 approved these changes

2024-08-20 14:49 UTC, Slep-wt submitted a review, later dismissed

2024-08-20 22:58 UTC, mattkelly4 commented
Sorry, just need to change A020 to A020V, standby on merging

2024-08-21 09:00 UTC, glennawatson requested changes

2024-08-21 09:04 UTC, mattkelly4 commented on docs/aerodromes/classc/Cairns.md
> +    CS ADC is responsible for issuing visual approach clearances to some aircraft tracking for runway 33 in CTA, as well as initial airways clearances for VFR aircraft entering the CTR from class G.
It's a quick note to indicate that ADC has additional responsibilities. They are outlined in detail by following the link

2024-08-21 09:08 UTC, alphadelta332 submitted a review, later dismissed

2024-08-21 09:14 UTC, mattkelly4 commented on docs/aerodromes/classc/Cairns.md
> +When instrument approaches are in use to runway 15, and visual separation is not possible due to the weather conditions (i.e. VMC does not exist below `A030`), do not issue a takeoff clearance to an
Sorry Glenn, this suggestion doesn't make a great deal of sense in my head. Might leave it as is.

2024-08-21 09:17 UTC, mattkelly4 commented on docs/aerodromes/classc/Cairns.md
> +ADC must assess any conflict with aircraft in the CTR and clear the inbound aircraft for a visual approach when suitable. Due to the small amount of airspace available, it is vital that ADC maintains
Still needs to reference separation *assurance*, not just separation here. I'll reword it to implement your other suggested wording changes.

2024-08-21 09:18 UTC, mattkelly4 commented on docs/aerodromes/classc/Cairns.md
> +VFR helicopters transit from the Reef to a floating pontoon helipad on the southeastern shore of the CBD, approximately 2nm from the runway 33 threshold. This helipad is referred to as 'The Pier'.
Appreciate the input but would prefer to leave this sentence structured as originally committed (avoids confusion around whether the helipad is 2nm from RWY33 or whether the CBD is 2nm from RWY33).

2024-08-21 09:19 UTC, mattkelly4 commented on docs/aerodromes/classc/Cairns.md
> +When visual approaches are in use, expect light & medium category aircraft (B737/A320 and below) to track via a straight in visual approach, or track via a visual right base. Aircraft inside CTA trac
Shall reword separately.

2024-08-21 09:59 UTC, alphadelta332 submitted a review, later dismissed

2024-08-21 11:50 UTC, tylerthetiletiler submitted a review, later dismissed

2024-08-25 11:24 UTC, alphadelta332 approved these changes

2024-08-27 01:24 UTC, tylerthetiletiler approved these changes

2024-09-03 03:05 UTC, LeGiraffe approved these changes

2024-09-03 03:06 UTC, merged