Add YSSY Curfew OPR INFO to ATIS section
vatpac-technology/sops pull request #379
Opened 2024-11-13 13:48 UTC by AgentWolfFBI

## Summary
Adds the curfew runway nomination OPR INFO line to the ATIS section for controllers who wish to simulate curfew mode operations.

## Changes
**Additions**:
- Curfew runway mode ATIS OPR INFO line.

2024-11-14 23:26 UTC, alphadelta332 requested changes
Not sure what that added temp.wav file is too, but I assume it doesn't need to be there

2024-11-14 23:26 UTC, alphadelta332 commented on docs/aerodromes/classc/Sydney.md
> +| Curfew Mode Operations | `CURFEW RWY NOMINATION. CURFEW IN OPERATION UNTIL TIME 1900.` |
This is 2000 during standard time. Perhaps include a note about what this should be during DST vs ST?

2024-11-20 00:38 UTC, mattkelly4 commented on docs/aerodromes/classc/Sydney.md
> +| | AEDT: `CURFEW RWY NOMINATION. CURFEW IN OPERATION UNTIL TIME 1900.` |
```suggestion
| Curfew Mode Operations | AEST: `CURFEW RWY NOMINATION. CURFEW IN OPERATION UNTIL TIME 2000.` <br>AEDT: `CURFEW RWY NOMINATION. CURFEW IN OPERATION UNTIL TIME 1900.` |
```

Having these both in a single cell on new lines might help to correlate them with the title in column 1 better

2024-11-23 01:33 UTC, alphadelta332 approved these changes

2024-11-23 03:43 UTC, mattkelly4 approved these changes
Thanks for contributing this @AgentWolfFBI

2024-11-23 04:03 UTC, tylerthetiletiler approved these changes

2024-11-23 04:03 UTC, merged