Admonition Changes
vatpac-technology/sops pull request #401
Opened 2024-12-13 07:02 UTC by alphadelta332

## Changes
**Fixes**:
- Fixed other custom admonitions that were showing without any formatting, such as _information, caution, and important_

**Additions**:
- Created new "Phraseology" Admonition (Separate from examples)
<img width="382" alt="firefox_vvDcemZuHi" src="https://github.com/user-attachments/assets/834bc5e2-ea7f-4bf2-a4cd-480539f906a3" />

2024-12-13 09:15 UTC, mattkelly4 requested changes

2024-12-13 09:15 UTC, mattkelly4 commented on docs/assist-us/best-practices.md
> -!!! example
This one might be better as an `example` since its highlighting how to format a radio call, rather than providing a phraseology case

2024-12-13 09:15 UTC, mattkelly4 commented on docs/assist-us/best-practices.md
> -!!! example
Same with this one

2024-12-13 09:49 UTC, mattkelly4 approved these changes

2024-12-15 00:35 UTC, tylerthetiletiler approved these changes

2024-12-15 21:23 UTC, merged