MK, RK, Pacific Ports
vatpac-technology/sops pull request #49
Opened 2022-11-17 16:57 UTC by tylerthetiletiler

Mackay Aerodrome
Rocky Aerodrome

Made a start on Pacific Ports

Removed VATNZ material

Amended TODO

2022-11-17 21:22 UTC, alexd-332 requested changes
Also apologies, Coral TCU owns up to F150, not F155 (finally found doc)

2022-11-17 21:22 UTC, alexd-332 commented on docs/aerodromes/Mackay.md
> +The Standard Assignable level from COR TCU to MK TWR is `A060`, any other level must be prior coordinated.
No standard assignable, just cleared for approach and transferred to tower prior to 10nm, or overhead the aid if doing VOR/NDB reversal

2022-11-17 21:22 UTC, alexd-332 commented on docs/aerodromes/Rockhampton.md
> +## Airspace
Note about RK TWR owning RK CTR SFC-A010

2022-11-17 21:22 UTC, alexd-332 commented on docs/aerodromes/Rockhampton.md
> +The Standard Assignable level from COR TCU to MK TWR is `A060`, any other level must be prior coordinated.
No standard assignable, just cleared for approach and transferred to tower prior 10nm, or overhead the aid if doing VOR/NDB reversal

2022-11-18 02:09 UTC, alexd-332 submitted a review, later dismissed

2022-11-18 04:07 UTC, alexd-332 approved these changes

2022-11-18 06:02 UTC, zkgell approved these changes
changes not required

2022-11-19 04:34 UTC, mattkelly4 approved these changes

2022-11-19 04:46 UTC, merged