Perth TCU
vatpac-technology/sops pull request #50
Opened 2022-11-18 02:11 UTC by tylerthetiletiler

Perth TCU Finalisation

Perth Tower Amendments

2022-11-18 02:27 UTC, chrisg06 submitted a review, later dismissed

2022-11-18 02:27 UTC, chrisg06 commented
approved

2022-11-18 02:27 UTC, zkgell submitted a review, later dismissed
approved

2022-11-18 02:57 UTC, alexd-332 requested changes

2022-11-18 02:57 UTC, alexd-332 commented on docs/terminal/perth.md
> +a) Class G cut out to the south
PH TCU is responsible for the Class G cutout

2022-11-18 02:57 UTC, alexd-332 commented on docs/terminal/perth.md
> +Voiceless coordination is in place from AD TCU to PIY (and subsectors) for aircraft:
and assigned a SID, or maybe "tracking via SID terminus"

2022-11-18 03:11 UTC, alexd-332 approved these changes

2022-11-18 06:00 UTC, zkgell approved these changes
approved

2022-11-19 05:12 UTC, zachbf approved these changes

2022-11-19 05:12 UTC, merged